<a href="https://colab.research.google.com/github/SoheilBadri2000/DataScience1/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import time # first solution
import timeit # third solution

# Create a list with 1 million items
my_list = list(range(1, 1_000_000))
# Create a numpy list with 1 million items
my_np_list = np.array(my_list)

# Calculate sum (and time)
start_time = time.time()
sum_list = sum(my_list)
end_time = time.time()
print(end_time - start_time)

start_time = time.time()
sum_array = np.sum(my_np_list)
end_time = time.time()
print(end_time - start_time)


0.006935834884643555
0.0014178752899169922


In [21]:
# magic function --> second solution
%timeit sum_list = sum(my_list)
%timeit sum_array = np.sum(my_np_list)

8.07 ms ± 1.82 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
728 µs ± 6.67 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
import pandas as pd

loadiris = load_iris()
X = loadiris.data
y = loadiris.target
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [25]:
lr_clf = LogisticRegression()
lr_clf.fit(X, y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [28]:
y[0]

0

In [30]:
lr_clf.predict([[5.1, 3.5, 1.4, 0.2]])

array([0])

In [31]:
lr_clf.predict([[5, 3.6, 1.3, 0.12]])

array([0])