<a href="https://colab.research.google.com/github/SoheilBadri2000/DataScience1/blob/main/ch02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v = np.array([[1,2,3]])

In [3]:
v

array([[1, 2, 3]])

In [4]:
v.T

array([[1],
       [2],
       [3]])

In [8]:
v = np.array([1,2,3,4,6,8,9])
v_dim = len(v) # 7
v_mag = np.linalg.norm(v)
v_mag # norm ---  ||v|| = 14.52583904633395

14.52583904633395

In [9]:
v_cap = (1/v_mag)*v
v_cap

array([0.06884284, 0.13768568, 0.20652852, 0.27537136, 0.41305703,
       0.55074271, 0.61958555])

In [10]:
# dot product (aTb)
v = np.array([1,2,3,4])
w = np.array([5,6,7,8])
np.dot(v,w)

70

In [11]:
np.dot(10*v,w)

700

In [12]:
np.dot(-10*v,w)

-700

In [ ]:
# aT(b+c) = aTb + aTc
a = np.array([0,1,2])
b = np.array([3,5,7])
c = np.array([13,21,34])

res = np.dot(a, b+c)